<a href="https://colab.research.google.com/github/Boyoung1206/boyoung/blob/main/CH03_03_copy%EB%A5%BC_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B3%B5%EC%82%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

copy를 이용한 데이터복사

- 데이터 생성

In [3]:
import pandas as pd
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})

- 문제: 필드명을 a,b,c에서 d,e,f로 변경하시오

In [4]:
df.columns=['d','e','f']

In [5]:
df

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9

- 문제: 필드명 a를 '에이'로 변경하시오.

In [7]:
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})

In [10]:
df.rename(columns = {'a':'에이'}, inplace = True)

In [11]:
df

   에이  b  c
0   1  4  7
1   2  5  8
2   3  6  9

- 변수명을 복제하여 해결???

In [12]:
# 처음에 변수를 2개 만들어 놓으면 다시 만들 필요 없음!!
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})
# 1개의 데이터 프페임을 2개의 변수명이 동시 사용하는것임
df2 = df # 얕은 복사

In [13]:
df

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [14]:
df2

   a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [15]:
df.columns=['d','e','f']

In [16]:
df

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9

In [17]:
df2

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9

- deep copy를 통한 해결

In [18]:
import copy

In [19]:
df = pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[7,8,9]})

In [27]:
# 각 데이터프레임을 따로 저장
df2 = copy.deepcopy(df)

In [28]:
df

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9

In [29]:
df2

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9

In [30]:
df.columns = ['d','e','f']

In [31]:
df

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9

In [32]:
df2

   d  e  f
0  1  4  7
1  2  5  8
2  3  6  9